language: ruby
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - ruby-head
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
script: "bundle exec rake spec"
